(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")

(depends-on "use-package")
(depends-on "ack-and-a-half")
(depends-on "cask")
(depends-on "elpy")
(depends-on "exec-path-from-shell")
(depends-on "flx-ido")
(depends-on "magit")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "neotree")
(depends-on "yasnippet")
(depends-on "zenburn-theme")
(depends-on "evil")
(depends-on "evil-surround")
(depends-on "evil-numbers")
(depends-on "evil-leader")
(depends-on "evil-search-highlight-persist")
(depends-on "color-theme-approximate")
(depends-on "ace-jump-mode")
(depends-on "helm")
(depends-on "helm-swoop")
(depends-on "helm-projectile")
(depends-on "auto-complete")
(depends-on "magit")
(depends-on "hydra")
(depends-on "company")
(depends-on "ycmd")
(depends-on "company-ycmd")
